#!/usr/bin/env bash
# Install piwallet-bonnet.service for a developer Pi (repo in $HOME, run as your user).
#
# Production sealed images use deploy/provision-pi.sh instead (/opt/piwallet, pwsv).
#
# Usage (on the Pi, after sync + install-piwallet-deps.sh):
#   bash scripts/setup-bonnet-service.sh
#   bash scripts/setup-bonnet-service.sh --repo ~/PiWallet --user pisv
#
# From your Mac (after sync-to-pi.sh):
#   ssh pisv@piwalletsv32.local 'cd ~/PiWallet && bash scripts/setup-bonnet-service.sh'
set -euo pipefail

readonly LOG_PREFIX="[setup-bonnet-service]"
readonly UNIT_NAME="piwallet-bonnet.service"
readonly JOURNALD_DROPIN="piwallet.conf"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_USER="$(whoami)"
VAULT_PATH="${HOME}/.piwallet/vault.bin"
DRY_RUN=0

usage() {
    sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
}

log() { printf '%s %s\n' "$LOG_PREFIX" "$*"; }

run() {
    if [[ $DRY_RUN -eq 1 ]]; then
        printf '%s DRY: %s\n' "$LOG_PREFIX" "$*"
    else
        "$@"
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo) REPO_ROOT=${2:?}; shift ;;
        --repo=*) REPO_ROOT=${1#--repo=} ;;
        --user) RUN_USER=${2:?}; shift ;;
        --user=*) RUN_USER=${1#--user=} ;;
        --vault-path) VAULT_PATH=${2:?}; shift ;;
        --vault-path=*) VAULT_PATH=${1#--vault-path=} ;;
        --dry-run) DRY_RUN=1 ;;
        -h|--help) usage ;;
        *) echo "unknown option: $1" >&2; usage ;;
    esac
    shift
done

PIWALLET_BIN="$REPO_ROOT/.venv/bin/piwallet"
if [[ ! -x "$PIWALLET_BIN" ]]; then
    echo "$LOG_PREFIX missing $PIWALLET_BIN — run: bash scripts/install-piwallet-deps.sh" >&2
    exit 1
fi

UNIT_TMP="$(mktemp)"
trap 'rm -f "$UNIT_TMP"' EXIT

cat >"$UNIT_TMP" <<EOF
# PiWalletSV bonnet UI — developer unit (generated by setup-bonnet-service.sh)
[Unit]
Description=PiWalletSV bonnet UI
After=network-pre.target graphical.target
Conflicts=getty@tty1.service

[Service]
Type=simple
User=${RUN_USER}
WorkingDirectory=${REPO_ROOT}
Environment=LIBCAMERA_LOG_LEVELS=*:WARN
Environment=PICAMERA2_LOG_LEVEL=0
Environment=PIWALLET_LOG_LEVEL=WARNING
ExecStart=${PIWALLET_BIN} bonnet --vault-path ${VAULT_PATH}
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

log "installing ${UNIT_NAME} for user=${RUN_USER}"
log "  repo:  ${REPO_ROOT}"
log "  vault: ${VAULT_PATH}"

run sudo install -m 0644 "$UNIT_TMP" "/etc/systemd/system/${UNIT_NAME}"

JOURNALD_SRC="$REPO_ROOT/deploy/systemd/journald-piwallet.conf.example"
if [[ -f "$JOURNALD_SRC" ]]; then
    run sudo install -d -m 0755 /etc/systemd/journald.conf.d
    run sudo install -m 0644 "$JOURNALD_SRC" "/etc/systemd/journald.conf.d/${JOURNALD_DROPIN}"
fi

run sudo systemctl daemon-reload
run sudo systemctl enable "${UNIT_NAME}"
run sudo systemctl restart "${UNIT_NAME}"

log "status:"
if [[ $DRY_RUN -eq 0 ]]; then
    systemctl is-active "${UNIT_NAME}" || true
    systemctl status "${UNIT_NAME}" --no-pager -n 15 || true
fi

log "done — bonnet starts on boot. Logs: journalctl -u ${UNIT_NAME} -f"
